In [13]:
# Imports for Pytorch
from __future__ import print_function
import argparse
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import random
import os
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.optim.lr_scheduler import StepLR
from skimage import io, transform

In [23]:
# Class for the dataset
class DetectionImages(Dataset):
    def __init__(self, csv_file, root_dir, transform=None):
        """
        Args:
            csv_file (string): Path to the csv file with annotations.
            root_dir (string): Directory with all the images.
            transform (callable, optional): Optional transform to be applied
                on a sample.
        """
        self.labels_df = pd.read_csv(csv_file, sep=" ", header=None)
        self.root_dir = root_dir
        self.transform = transform

    def __len__(self):
        return len(self.labels_df)

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()

        img_name = os.path.join(self.root_dir,
                                self.labels_df.iloc[idx, 0])
        image = io.imread(img_name)
        label = self.labels_df.iloc[idx, 1:]
        sample = {'image': image, 'label': label}

        if self.transform:
            sample = self.transform(sample)

        return sample

class ToTensor(object):
    """Convert ndarrays in sample to Tensors."""

    def __call__(self, sample):
        image, label = sample['image'], sample['label']
        in_transform = transforms.Compose([transforms.Normalize([146.5899, 142.5595, 139.0785], [34.5019, 34.8481, 37.1137])])
        # swap color axis because
        # numpy image: H x W x C
        # torch image: C X H X W
        image = image.transpose((2, 0, 1))
        image = torch.from_numpy(image).float()
        image = in_transform(image)
        return {'image': image,
                'label': torch.from_numpy(np.array(label).astype(int))}


In [24]:
# Load in the training and testing datasets. Convert to pytorch tensor.
train_data = DetectionImages(csv_file="../data/labels/class_train_labels.txt", root_dir="../data/train", transform=ToTensor())

for idx, batch_sample in enumerate(train_data):
    print(batch_sample["label"])

tensor([26], dtype=torch.int32)
tensor([33], dtype=torch.int32)
tensor([77], dtype=torch.int32)
tensor([13], dtype=torch.int32)
tensor([82], dtype=torch.int32)
tensor([38], dtype=torch.int32)
tensor([73], dtype=torch.int32)
tensor([21], dtype=torch.int32)
tensor([61], dtype=torch.int32)
tensor([83], dtype=torch.int32)
tensor([48], dtype=torch.int32)
tensor([84], dtype=torch.int32)
tensor([45], dtype=torch.int32)
tensor([61], dtype=torch.int32)
tensor([77], dtype=torch.int32)
tensor([32], dtype=torch.int32)
tensor([85], dtype=torch.int32)
tensor([62], dtype=torch.int32)
tensor([87], dtype=torch.int32)
tensor([87], dtype=torch.int32)
tensor([22], dtype=torch.int32)
tensor([94], dtype=torch.int32)
tensor([66], dtype=torch.int32)
tensor([33], dtype=torch.int32)
tensor([89], dtype=torch.int32)
tensor([29], dtype=torch.int32)
tensor([48], dtype=torch.int32)
tensor([87], dtype=torch.int32)
tensor([34], dtype=torch.int32)
tensor([23], dtype=torch.int32)
tensor([26], dtype=torch.int32)
tensor([